---
- name: Master-Playbook für vollständige Harvester-Installation und -Konfiguration
  hosts: harvester_host
  become: yes
  gather_facts: false

- import_playbook: playbooks/harvester_install.yml
  tags:
    - install

- import_playbook: playbooks/install_packages.yml
  tags:
    - packages

- import_playbook: playbooks/setup_bridge.yml
  tags:
    - bridge

- import_playbook: playbooks/configure_snat.yml
  tags:
    - snat

- import_playbook: playbooks/configure_multus.yml
  tags:
    - multus
