---
- name: Konfiguriere SNAT-Regeln
  hosts: harvester_host
  gather_facts: False
  tasks:
  - wait_for_connection: 
      timeout: 1
    ignore_errors: yes
    register: user_connection
    tags: always
  - set_fact:
      connect_user: "{{'root' if user_connection.failed else ansible_user }}"
    tags: always

  - name: SNAT Regel hinzufügen
    iptables:
      table: nat
      chain: POSTROUTING
      source: 192.168.100.0/24
      out_interface: eth0
      jump: MASQUERADE

  - name: Speichere die iptables-Regeln
    shell: iptables-save > /etc/iptables/rules.v4
    when: ansible_os_family == "Debian"

  - name: Aktivieren von iptables-persistent
    service:
      name: netfilter-persistent
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"
